FIREBASE_API_KEY = "AIzaSyC_F6_lZgoQgnpXpOBN0tXIhsvyHPrsf60"
FIREBASE_AUTH_DOMAIN= "social-chat-5f7ed.firebaseapp.com"
FIREBASE_DATABASE_URL = "https://social-chat-5f7ed-default-rtdb.europe-west1.firebasedatabase.app/"
FIREBASE_PROJECT_ID = "social-chat-5f7ed"
FIREBASE_STORAGE_BUCKET = "social-chat-5f7ed.appspot.com"
FIREBASE_MESSAGING_SENDER_ID = "901335327454"
FIREBASE_APP_ID = "1:901335327454:web:e21e515f135cb10f02584f"
FIREBASE_MEASURE = "G-5DT34CSZ35"
